version: "3.9"
services:
    pg_db:
        image: postgres:latest
        container_name: pg_db
        restart: always
        ports: 
            - "5432:5432"
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 30s
            timeout: 10s
            retries: 5

    api:
        image: thoersch/todo-list-api-nest-js
        build:
            dockerfile: Dockerfile
            context: .
        restart: on-failure
        depends_on:
            - pg_db
        environment: 
            PORT: 3000
            WAIT_HOSTS: pg_db:5432
        ports:
            - "8080:3000"